name: mnc_identifier_face
description: MNC liveness detection flutter plugin
version: 1.0.0
homepage: https://mobile.mncinnovation.id/docs/mncidentifier/overview
repository: https://github.com/mncinnovation/mnc_identifier_face

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: id.mncinnovation.mnc_identifier_face
        pluginClass: MncIdentifierFacePlugin
      ios:
        pluginClass: MncIdentifierFacePlugin

  